### ISSUE TITLE
Error when paired with eupRate

### ISSUE THREAD

**Issue by Alexander-Kahanek** [holtzy/R-Markdown-Parallax#1]
I am attempting to combine the parallax and epuRate theme together, however it seems to running into an issue.

Here is my header, with the information removed:

```
---
title: "x"
author: "x"
date: "x"
mail: "x"
#linkedin: ""
#twitter: ""
github: "x"
home: "x"
logo: "x"
output:
  epuRate::epurate:
    css: style.css
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
    includes: 
        before_body: header.html
---
```

and here is the error message it is giving me: 

```
Error in (function (toc = TRUE, code_folding = "hide", number_sections = TRUE)  : 
  unused arguments (css = "style.css", includes = list("header.html"))
Calls: <Anonymous> -> create_output_format -> do.call
Execution halted
```

The files were copied directly, so I do not believe it is not the actual style.css and header.html files themselves.
